name: CI

on:
  push:
    branches: [ main, deploy/* ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: echo "DATABASE_URL=file:./dev.db" > .env
      - run: npx prisma db push
      - run: npx tsx prisma/seed.ts
        env:
          MOCK_DONUT_API: http://localhost:4000
      - run: npm run build

